### ISSUE TITLE
Bluetooth Unavailable After Restart

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#18]
```
ERROR (MainThread) [homeassistant.components.bluetooth_tracker.device_tracker] Error looking up Bluetooth device
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/bluetooth/bluez.py", line 30, in discover_devices
      results = _bt.hci_inquiry (sock, duration=duration, flush_cache=True,
  _bluetooth.error: (110, 'Operation timed out')

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 138, in perform_bluetooth_update
      devices = await hass.async_add_executor_job(discover_devices, device_id)
    File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
      result = self.fn(*self.args, **self.kwargs)
    File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 56, in discover_devices
      result = bluetooth.discover_devices(
    File "/usr/local/lib/python3.8/site-packages/bluetooth/bluez.py", line 34, in discover_devices
      raise BluetoothError ("error communicating with local "
  bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter
```

**Comment by jazzyisj** [comment]
This seems to have been resolved with HASS OS 6.1?
