### ISSUE TITLE
Alert Error - Extra keys not allowed @ data['data']

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#20]
```
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/core.py", line 1442, in async_call
      processed_data = handler.schema(service_data)
    File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
      return self._compiled([], data)
    File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
      return base_validate(path, iteritems(data), out)
    File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
      raise er.MultipleInvalid(errors)
  voluptuous.error.MultipleInvalid: extra keys not allowed @ data['data']
```

**Comment by jazzyisj** [comment]
Tried to use persistent notification together with mobile notification.  Persistent didn't like data tag.

```
  - platform: group
    name: system
    services:
      # - service: persistent_notification #ISSUE this doesn't this work?
      #ERROR MultipleInvalid: extra keys not allowed @ data['data']
      - service: jason
```
